config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 

  get 'home/about' => 'home#about',as: 'about'
 

  root to: 'homes#top'

  get 'homes/new'
  get 'homes/index'
  get 'homes/show'

  

  resources :books, only: [:new, :index, :create, :edit, :show]
  resources :users, only: [:index, :show, :edit, :update]
  
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id'=> 'books#destroy', as: 'destroy_book'  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates:title, presence: true
    validates:body,length: {maximum: 200}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates:name,length: {in:2..20}, presence: true, uniqueness: true
  validates:introduction,length: {maximum: 50}
  #validates:image, presence: true

  def get_profile_image(width,height)

    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top,:about]
    before_action :configure_permitted_parameters, if: :devise_controller?
    
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end
    
end

app/controllers/books_controller.rb
 before_action :is_matching_login_user, only: [:edit,:update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
     if @book.save
       flash[:notice] = "You have created book successfully."
        redirect_to book_path(@book.id)
     else
       @books = Book.all
       @user = current_user
        render :index
     end
  end


  def index
    @books = Book.all.order(created_at: :desc)
    @user = current_user
    @book = Book.new
  end

  def show
    @books = Book.find(params[:id])
    @user = @books.user
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have update book successfully."
     redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
    redirect_to user_path(@user.id)
    else
      flash[:alert] = "err"
     render :edit
    end  
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<% if book.errors.any? %>
    <%= book.errors.count %>件エラーが発生しました
    <ul>
        <% book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
    </ul>
<% end %>

<div>
    <%= flash[:notice] %>
</div>


<h2>User info</h2>

<div>
   <%= image_tag user.get_profile_image(100,100)%>
<table class="table table-striped">
    <tbody>
    <tr>
        <td>name</td>
        <td><%= user.name %></td>
    </tr>
    <tr>
        <td>introduction</td>
        <td><%= user.introduction %></td></tr>
    </tbody>
</table>
</div>


<p><%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<% end %>
</p>


<div>
<h2 class="mt-3">New book</h2>

<%= form_with model: book do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<div class="form-grope">
<%= f.submit 'Create Book',class: "btn btn-secondary" %>
</div>
<% end %>
</div>

app/views/books/edit.html.erb
<% if flash[:notice] %>
<p id= "notice">
    <%= flash[:notice] %>
</p>
<% end %>

<h1>Editing Book</h1>
<% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this obj from being saved
    <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
<% end %>    

<%= form_with model: @book, url: update_book_path do |f| %>

<p>title</p>
<%= f.text_field :title %>

<p>Opinion</p>
<%= f.text_area :body %>
<%= f.submit 'Update Book' %>

<% end %>

 <%=link_to "Show", book_path(@book.id) %>
 
 <%=link_to "Back", books_path %>

app/views/books/index.html.erb
<div class = " container">
    <div class ="row">
        <div class = "col-md-3">

<%= render 'book', book: @book, user: @user %>
</div>
   <div class = "col-md-8 offset-md-1">
   

<h1>Books</h1>
<table class="table table-striped">
   <thead>
       <tr>
           <th>Title</th>
           <th>Opinion</th>
       </tr>
   </thead>
   <tbody>

       <% @books.each do |book| %>
       <tr>
           <td><%= link_to user_path(book.user.id) do %>
               <%= image_tag @user.get_profile_image(100,100) %>
               <% end %></td>
           <td><%= link_to book.title, "/books/#{book.id}" %></td>
           <td><%= book.body %></td>
       </tr>
       <% end %>
   </tbody>
</table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class = " container">
    <div class ="row">
        <div class = "col-md-3">

<%= render 'book', book: @book, user: @user %>
</div>
<div class = "col-md-8 offset-md-1">
       


<h1>Book detail</h1>
<table class="table table-striped">
 <tbody>
    <tr>
    <td><%= image_tag @books.user.get_profile_image(100,100) %></td>
<td><%= link_to @books.user.name, "/users/#{@books.user.id}" %></td>
<td><%= @books.title %></td>
<td><%= @books.body %></td>

<td><% if @books.user ==  current_user %>
 <%= link_to "Edit", edit_book_path(@books.id) %>
 <% end %></td>

<td><% if @books.user ==  current_user %>
<%= link_to "Destroy", destroy_book_path, method: :delete, "data-confirm" => "本当に消しますか?" %>
<% end %></td>
</tr>
</tbody>
</table>

 </div>
 </div>

app/views/home/about.html.erb
<div class="container">
    <div class="row">
<h1 class= "px-3 mx-auto">Welcome to <i class="fa-solid fa-book"></i>
<strongs>Bookers!</strongs></h1>
    </div>
</div>

app/views/homes/top.html.erb
<div>
    <%= flash[:notice] %>
</div>

<div class="container">
    <div class="row"> 
     <div class="mx-auto col-11 col-sm-10 col-lg-8 col-x1-6">
<h1>welcom to <i class="fa-solid fa-book"></i>Bookers</h1>
<p>In <i class="fa-solid fa-book"></i>Bookers,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>
     
    


<div class="btn btn-wrapper col-10 mx-auto">
    <div class="row">
        <div class="btn btn-info btn-sm btn-block mb-3" style= "background-color:#17a2b8;" >
        <%= link_to "Log in", new_user_session_path, class: 'nav-link text-white'%>
        </div>
    </div>


    <div class="row">
        <div class="btn btn-success btn-sm btn-block mb-3" style="background-color:#28a745;">
        <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-white' %>
        </div>
    </div>
</div>
    </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f9bd706c8c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm" style=background-color:#343a40;>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand a-link text-white" href="/">Bookers</a>
        <ul class= "navbar-nav ml-auto">
      <% if user_signed_in? %>

        <li class="nav-item">
          <i class="fas fa-home"></i>
          <%= link_to "Home", user_path(current_user.id), class: 'nav-link text-white' %>
          
        </li>
        <li class="nav-item">
          <i class="fas fa-users"></i>
          <%= link_to "Users", users_path, class:'nav-link text-white' %>
        </li>
        <li class="nav-item">
           <i class="fas fa-book-open"></i>
          <%= link_to "Books", books_path, class:'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <i class="fas fa-sign-out-alt"></i>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
      <% else %>
        <li class="nav-item">
          <i class="fas fa-home" ></i>#
          <%= link_to "Home", root_path, class: 'nav-link text-white' %>
          
        </li>
        <li class="nav-item">
          <i class="fas fa-link"></i>
          <%= link_to "About", about_path, class: 'nav-link text-white' %>
        </li>

        <li class="nav-item">
          <i class="fas fa-user-plus"></i>
          <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-white' %>
        </li>

        <li class="nav-item">
          <i class="fas fa-sign-in-alt"></i>
          <%= link_to "Log in", new_user_session_path, class: 'nav-link text-white'%>
        </li>

      <% end %>
        </ul>
         </div>
      </nav>
    </header>

    <main>
    <%= yield %>
    </main>
    <footer>
      <div class="text-center">
        <div class="container mt-4"
      <p>CopyRight Infratop.inc</p>
      </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if flash[:notice] %>
<p id= "notice">
    <%= flash[:notice] %>
</p>
<% end %>

<% if @user.errors.any? %>
    <%= @user.errors.count %>errors prohibited this obj from being saved
    <ul>
    <% @user.errors.full_messages.each do |message| %>
     <li><%= message %></li>
<% end %>
    </ul>
<% end %>    
<h1>User info</h1>
 <%= form_with model: @user do |f| %>
     <label for="inputName">Name</label>
     <%= f.text_field :name, autofocus: true, id:"inputName", placecholder:"名前"%>
     <label for="inputImage">Image</label>
     <%= f.file_field :profile_image, placecholder: "プロフィール画像", accept: "image/*",size: "200*200"%>
     <label for="inputIntroduction">Introduction</label>
     <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placecholder:"自己紹介"%>
     <%= f.submit "Update User" %>
 <% end %>
 

app/views/users/index.html.erb
<div class = " container">
    <div class ="row">
        <div class = "col-md-3">
            
<%= render 'books/book', book: @book, user: @user %>
</div>

<div class ="col-md-8 offset-md-1">

<h2>Users</h2>
<table class="table table-striped">
    <thead>
        <tr>
        <th>iamge</th>
        <th>name</th>
        <th></th>
        </tr>
    </thead>
    <tbody>
<% @users.each do |user| %>
    <tr>
    <td><%= image_tag user.get_profile_image(100,100) %></td>
    <td>name<%= user.name %></td>

    <td><%= link_to "Show", user_path(user.id) %></td>
</tr>
<% end %>
</tbody>
</table>
        
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class = " container">
    <div class ="row">
        <div class = "col-md-3">

<%= render 'books/book', book: @book, user: @user %>
</div>
        <div class = "col-md-8 offset-md-1">

    
<h1>Books</h1>
<table class="table table-striped">
   <thead>
       <tr>
           <th>Title</th>
           <th>Opinion</th>
       </tr>
   </thead>
   <tbody>
 <% @books.each do |book| %>
       <tr>
           <td><%= link_to user_path(book.user.id) do %>
               <%= image_tag @user.get_profile_image(100,100) %>
               <% end %>
           </td>
           <td><%= link_to book.title, "/books/#{book.id}" %></td>
           <td><%= book.body %></td>
       </tr>
       <% end %>
</tbody>
</table>
        
     </div>
</div>